### ISSUE TITLE
Add data folder to project and add the folder's path to .gitignore

### ISSUE THREAD

**Issue by mrcolo** [datares/stock_predictor#2]
As mentioned in our meeting, we need a path for the data folder where you all are going to add your CSVs. We also need to add that path to the .gitignore so that when pushing, we are not going to have to upload dozens of MBs.

You can add a FOLDER to the gitignore by adding
`name_of_directory/`

to the file.

**Comment by Ashish1999Kumar** [comment]
Hello ,I would like to work on this issue.
I have a question do we have to create a data folder and then add its address to git ignore??

**Comment by mrcolo** [comment]
It’s not required, but I would advise doing it to check that your command ‘git add .’ Works properly (meaning, it doesn’t actually add the folder to your online repo when you push)

Francesco Colonnese

**Comment by mrcolo** [comment]
@Ashish1999Kumar how is this working out for you? I saw you closed a pull request.

**Comment by Ashish1999Kumar** [comment]
I closed the previous pull request because it had too many bogus commits..i already sent a new pull request..in that the Data Folder is present in the local file system and not in the github repository.So Check whether that is what you wanted me to do.
