### ISSUE TITLE
Change the directory setup and merge in utils.py

### ISSUE THREAD

**Issue by mrcolo** [datares/stock_predictor#8]
I noticed a problem with the way the directory is structured at the moment. 
common.py is currently organized in a way such as:
`src/preprocess`

Usually, when building a framework, we wanna keep the "library" or "lib" in one single directory. Think of it as a "src" directory. Within it, there should also be a utils.py. What yall should do is copy the content of common.py to utils.py, because what it does is, for the most part, utils functions. 

Feel free to modify any file, just try to respect the directory structure next time you're working on adding a feature.

Cheers

**Comment by mrcolo** [comment]
@ieching I can't merge your code until the directory issue is fixed, just fyi :)

**Comment by ieching** [comment]
@mrcolo i fixed the directory issue on my branch; is there any other thing I can do to fix it?
